#define _XOPEN_SOURCE 700
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>

int nfork (int nb_fils){
	int cpt=0;
	pid_t pid;
	printf("generate %d fils----------------\n",nb_fils);
	for (int i=0;i<nb_fils;i++){	
		if ((pid=fork())== -1){
			perror ("fork() failed");
			break;		//exit for()
		}
		if (pid==0){			
			printf("pid:%d Im a fils\n",getpid());
			return 0;
			printf("fils didnt quit!!!!\n");
		}else{
			cpt++;	//nb_fils++; X also a condition in the for()
		}
	}
	if (nb_fils==0)
		return -1;
	else
		return cpt;
}

int main (int argc , char* argv[]){
	if (argc!=2){
		perror("Pls add a number as argument");
		return -1;
	}
	int nb = atoi(argv[1]);	//atoi ASCII string to Integer
	printf("%d entered\t %d process generated by nfork\n",nb,nfork(nb));
	return 0;
}
